version: '3.7'
services:
    mongodb:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        expose:
            - "6379"
        ports:
            - "27017:27017"